---
# Per environment values which override defaults in hmpps-ciag-careers-induction-api/values.yaml

generic-service:
  ingress:
    host: hmpps-ciag-careers-induction-api.hmpps.service.justice.gov.uk
    API_BASE_URL_OAUTH: https://sign-in.hmpps.service.justice.gov.uk/auth

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service
