create table IF NOT EXISTS ability_to_work_impact (offender_id varchar(255) not null, work_impact integer);
create table IF NOT EXISTS achieved_qualification (work_interests_id bigint not null, grade varchar(255), level integer, subject varchar(255));
create table IF NOT EXISTS ciag_profile (offender_id varchar(255) not null, other_ability_to_work_impact varchar(255), created_by varchar(255), created_date_time timestamp, desire_to_work boolean, hoping_to_get_work integer, modified_by varchar(255), modified_date_time timestamp, reason_to_not_get_work varchar(255), schema_version varchar(255), prison_work_and_education_id bigint, education_and_qualification_id bigint, skills_and_interests_id bigint, previous_work_id bigint, primary key (offender_id));
create table IF NOT EXISTS  reason_to_not_work (offender_id varchar(255) not null, reason integer);
create table IF NOT EXISTS current_work_interests (id bigint not null, modified_by varchar(255), modified_date_time timestamp, other_work_interest varchar(255), primary key (id));
create table IF NOT EXISTS education_qualification (id bigint not null, other_qualification varchar(255), education_level integer, modified_by varchar(255), modified_date_time timestamp, primary key (id));
create table IF NOT EXISTS extra_qualification (work_interests_id bigint not null, qualification integer);
create table IF NOT EXISTS particular_work_interests (work_interests_id bigint not null, role varchar(255), work_interest integer);
create table IF NOT EXISTS personal_work_interests (work_interests_id bigint not null, personal_work_interest integer);
create table IF NOT EXISTS previous_work (id bigint not null, has_worked_before boolean not null, modified_by varchar(255), modified_date_time timestamp, work_experience_other varchar(255), work_interests_id bigint, primary key (id));
create table IF NOT EXISTS prison_education (prison_work_education_id bigint not null, education integer);
create table IF NOT EXISTS prison_work (prison_work_education_id bigint not null, work integer);
create table IF NOT EXISTS prison_work_education (id bigint not null, other_prison_education varchar(255), other_prison_work varchar(255), modified_by varchar(255), modified_date_time timestamp, primary key (id));
create table IF NOT EXISTS skills_and_interests (id bigint not null, modified_by varchar(255), modified_date_time timestamp, other_personal_intrests varchar(255), other_skill varchar(255), primary key (id));
create table IF NOT EXISTS skills_work_interests (work_interests_id bigint not null, skills integer);
create table IF NOT EXISTS work_experience (previous_work_id bigint not null, work_experience integer);
create table IF NOT EXISTS work_experience_detail (previous_work_id bigint not null, details varchar(255), other_work varchar(255), role varchar(255), type_of_work_experience integer);
create table IF NOT EXISTS work_interests (work_interests_id bigint not null, work_interests integer);

alter table  ability_to_work_impact drop constraint  IF EXISTS    ability_to_work_impact_ciag_profile_FK ;
alter table achieved_qualification drop constraint  IF EXISTS  achieved_qualification_education_qualification_FK ;
alter table ciag_profile drop constraint  IF EXISTS    ciag_profile_prison_work_education_FK ;
alter table ciag_profile drop constraint  IF EXISTS   ciag_profile_education_qualification_FK ;
alter table ciag_profile drop constraint  IF EXISTS   ciag_profile_skills_and_interests_FK ;
alter table ciag_profile drop constraint  IF EXISTS  ciag_profile_previous_work_FK ;
alter table extra_qualification drop constraint  IF EXISTS   extra_qualification_education_qualification_FK ;
alter table particular_work_interests drop constraint  IF EXISTS   particular_work_interests_current_work_interests_FK ;
alter table personal_work_interests drop constraint  IF EXISTS  personal_work_interests_skills_and_interests_FK ;
alter table previous_work drop constraint  IF EXISTS   previous_work_current_work_interests_FK ;
alter table prison_education drop constraint  IF EXISTS  prison_education_prison_work_education_FK ;
alter table prison_work drop constraint  IF EXISTS   prison_work_prison_work_education_FK ;
alter table skills_work_interests drop constraint  IF EXISTS  skills_work_interests_skills_and_interests_FK ;
alter table work_experience drop constraint  IF EXISTS   work_experience_previous_work_FK ;
alter table work_experience_detail drop constraint  IF EXISTS   work_experience_detail_previous_work_FK ;
alter table work_interests drop constraint  IF EXISTS    work_experience_detail_current_work_interests_FK;
alter table reason_to_not_work drop constraint  IF EXISTS  reason_to_not_work_ciag_profile_FK;

alter table  ability_to_work_impact add constraint   ability_to_work_impact_ciag_profile_FK foreign key (offender_id) references ciag_profile;
alter table achieved_qualification add constraint achieved_qualification_education_qualification_FK foreign key (work_interests_id) references education_qualification;
alter table ciag_profile add constraint   ciag_profile_prison_work_education_FK foreign key (prison_work_and_education_id) references prison_work_education;
alter table ciag_profile add constraint  ciag_profile_education_qualification_FK foreign key (education_and_qualification_id) references education_qualification;
alter table ciag_profile add constraint  ciag_profile_skills_and_interests_FK foreign key (skills_and_interests_id) references skills_and_interests;
alter table ciag_profile add constraint ciag_profile_previous_work_FK foreign key (previous_work_id) references previous_work;
alter table extra_qualification add constraint  extra_qualification_education_qualification_FK foreign key (work_interests_id) references education_qualification;
alter table particular_work_interests add constraint  particular_work_interests_current_work_interests_FK foreign key (work_interests_id) references current_work_interests;
alter table personal_work_interests add constraint  personal_work_interests_skills_and_interests_FK foreign key (work_interests_id) references skills_and_interests;
alter table previous_work add constraint  previous_work_current_work_interests_FK foreign key (work_interests_id) references current_work_interests;
alter table prison_education add constraint prison_education_prison_work_education_FK foreign key (prison_work_education_id) references prison_work_education;
alter table prison_work add constraint  prison_work_prison_work_education_FK foreign key (prison_work_education_id) references prison_work_education;
alter table skills_work_interests add constraint skills_work_interests_skills_and_interests_FK foreign key (work_interests_id) references skills_and_interests;
alter table work_experience add constraint   work_experience_previous_work_FK foreign key (previous_work_id) references previous_work;
alter table work_experience_detail add constraint  work_experience_detail_previous_work_FK foreign key (previous_work_id) references previous_work;
alter table work_interests add constraint   work_experience_detail_current_work_interests_FK foreign key (work_interests_id) references current_work_interests;
alter table reason_to_not_work add constraint   reason_to_not_work_ciag_profile_FK foreign key (offender_id) references ciag_profile;

create sequence IF NOT EXISTS hibernate_seq start with 1 increment by 50;
create sequence IF NOT EXISTS education_qualification_seq start with 1 increment by 50;
create sequence IF NOT EXISTS current_work_interests_seq start with 1 increment by 50;
create sequence IF NOT EXISTS previous_work_seq start with 1 increment by 50;
create sequence IF NOT EXISTS skills_and_interests_seq start with 1 increment by 50;
create sequence IF NOT EXISTS prison_work_education_seq start with 1 increment by 50;
