create table IF NOT EXISTS ability_to_work_impact (offender_id varchar(255) not null, work_impact_ integer);
create table IF NOT EXISTS achieved_qualification (work_interests_id bigint not null, grade varchar(255), level integer, subject varchar(255));
create table IF NOT EXISTS ciag_profile (offender_id varchar(255) not null, other_ability_to_work_impact varchar(255), created_by varchar(255), created_date_time timestamp, desire_to_work boolean, hoping_to_get_work integer, modified_by varchar(255), modified_date_time timestamp, reason_not_to_get_work integer, reason_to_not_get_work varchar(255), schema_version varchar(255), primary key (offender_id));
create table IF NOT EXISTS current_work_interests (id bigint not null, modified_by varchar(255), modified_date_time timestamp, other_work_interest varchar(255), previous_work_id bigint, primary key (id));
create table IF NOT EXISTS education_qualification (id bigint not null, other_qualification varchar(255), education_level integer, modified_by varchar(255), modified_date_time timestamp, offender_id varchar(255), primary key (id));
create table IF NOT EXISTS extra_qualification (work_interests_id bigint not null, qualification integer);
create table IF NOT EXISTS particular_work_interests (work_interests_id bigint not null, role varchar(255), work_interest integer);
create table IF NOT EXISTS personal_work_interests (work_interests_id bigint not null, personal_work_interest integer);
create table IF NOT EXISTS previous_work (id bigint not null, has_worked_before boolean not null, modified_by varchar(255), modified_date_time timestamp, work_experience_other varchar(255), offender_id varchar(255), primary key (id));
create table IF NOT EXISTS prison_education (prison_work_education_id bigint not null, education integer);
create table IF NOT EXISTS prison_work (prison_work_education_id bigint not null, work integer);
create table IF NOT EXISTS prison_work_education (id bigint not null, other_prison_education varchar(255), other_prison_work varchar(255), modified_by varchar(255), modified_date_time timestamp, offender_id varchar(255), primary key (id));
create table IF NOT EXISTS skills_and_interests (id bigint not null, modified_by varchar(255), modified_date_time timestamp, other_personal_intrests varchar(255), other_skill varchar(255), offender_id varchar(255), primary key (id));
create table IF NOT EXISTS skills_work_interests (work_interests_id bigint not null, skills integer);
create table IF NOT EXISTS work_experience (previous_work_id bigint not null, work_experience integer);
create table IF NOT EXISTS work_experience_detail (previous_work_id bigint not null, details varchar(255), other_work varchar(255), role varchar(255), type_of_work_experience integer);
create table IF NOT EXISTS work_interests (work_interests_id bigint not null, work_interests integer);
create sequence IF NOT EXISTS hibernate_sequence start with 1 increment by 1;
alter table ability_to_work_impact add constraint IF NOT EXISTS ability_to_work_impact_ciag_profile foreign key (offender_id) references ciag_profile;
alter table achieved_qualification add constraint IF NOT EXISTS achieved_qualification_education_qualification foreign key (work_interests_id) references education_qualification;
alter table current_work_interests add constraint IF NOT EXISTS current_work_interests_previous_work foreign key (previous_work_id) references previous_work;
alter table education_qualification add constraint IF NOT EXISTS education_qualification_ciag_profile foreign key (offender_id) references ciag_profile;
alter table extra_qualification add constraint IF NOT EXISTS extra_qualification_education_qualification foreign key (work_interests_id) references education_qualification;
alter table particular_work_interests add constraint IF NOT EXISTS particular_work_interests_current_work_interests foreign key (work_interests_id) references current_work_interests;
alter table personal_work_interests add constraint IF NOT EXISTS personal_work_interests_skills_and_interests foreign key (work_interests_id) references skills_and_interests;
alter table previous_work add constraint IF NOT EXISTS previous_work_ciag_profile foreign key (offender_id) references ciag_profile;
alter table prison_education add constraint IF NOT EXISTS prison_education_prison_work_education foreign key (prison_work_education_id) references prison_work_education;
alter table prison_work add constraint IF NOT EXISTS prison_work_prison_work_education foreign key (prison_work_education_id) references prison_work_education;
alter table prison_work_education add constraint IF NOT EXISTS prison_work_education_ciag_profile foreign key (offender_id) references ciag_profile;
alter table skills_and_interests add constraint IF NOT EXISTS skills_and_interests_ciag_profile foreign key (offender_id) references ciag_profile;
alter table skills_work_interests add constraint IF NOT EXISTS skills_work_interests_skills_and_interests foreign key (work_interests_id) references skills_and_interests;
alter table work_experience add constraint IF NOT EXISTS work_experience_previous_work foreign key (previous_work_id) references previous_work;
alter table work_experience_detail add constraint IF NOT EXISTS work_experience_detail_previous_work foreign key (previous_work_id) references previous_work;
alter table work_interests add constraint IF NOT EXISTS work_interests_current_work_interests foreign key (work_interests_id) references current_work_interests;