drop table IF EXISTS ability_to_work_impact;
drop table IF EXISTS achieved_qualification;
drop table IF EXISTS extra_qualification ;
drop table IF EXISTS particular_work_interests;
drop table IF EXISTS personal_work_interests;
drop table IF EXISTS prison_education;
drop table IF EXISTS prison_work ;
drop table IF EXISTS prison_work_education;
drop table IF EXISTS skills_work_interests ;
drop table IF EXISTS work_experience;
drop table IF EXISTS work_experience_detail ;
drop table IF EXISTS work_interests;
drop table IF EXISTS skills_and_interests;
drop table IF EXISTS ciag_profile CASCADE;
drop table IF EXISTS previous_work CASCADE;
drop table IF EXISTS education_qualification ;
drop table IF EXISTS current_work_interests;
